export const FETCH_VEHICLES = 'FETCH_VEHICLES';
export const FETCH_VEHICLES_LOADING = 'FETCH_VEHICLES_LOADING';
export const SET_SELECTED_VEHICLE = 'SET_SELECTED_VEHICLE';
export const CLEAR_SELECTED_VEHICLE = 'CLEAR_SELECTED_VEHICLE';
